[book]
authors = ["pilipinas"]
language = "en"
multilingual = false
src = "src"
title = "Philippines Web Directory"

[output.html]
theme = "src/theme"
default-theme = "rust"
git-repository-url = "https://github.com/code-ink-space/directoryph"
git-repository-icon = "fa-github"
